version: '3'

services:
  web-app:
    #image: nginx:latest
    build: ./docker/web
    restart: always
    volumes:
      - ./html:/var/www/html
    environment:
      VIRTUAL_HOST: 'seg-server.local'
    ports:
      - 8091:80
    extra_hosts:
      - host.docker.internal:host-gateway

  php-app:
    build: ./docker/php
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./src:/var/www/src
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
